dist: xenial

cache:
  bundler: true
  directories:
    - node_modules

services:
  - redis-server
  - mysql

notifications:
  webhooks: https://coveralls.io/webhook?service_name=travis-ci

addons:
  chrome: stable

_ruby_job: &ruby_job
  language: ruby
  before_install:
    - nvm install v10.17.0
    - gem update bundler

_pageflow_ruby_job: &pageflow_ruby_job
  <<: *ruby_job
  rvm: 2.3.1
  before_script:
    - yarn install
    - bin/build-packages

    - bin/rake pageflow:dummy
    - WEBPACKER_PRECOMPILE=false bin/rake app:assets:precompile
  script: bin/rspec

jobs:
  include:
    - name: Percy - pageflow-scrolled
      <<: *ruby_job
      before_script:
        - |
          export ON_UPSTREAM_MASTER=$([[ "$TRAVIS_PULL_REQUEST" == "false" && \
                                         "$TRAVIS_REPO_SLUG" == "tf/pageflow" && \
                                         "$TRAVIS_BRANCH" == "gh-travis" ]] && echo "true" || echo "false")

          if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$ON_UPSTREAM_MASTER" == "false" ]]; then
            echo "Stopping job: Neither upstream master nor PR."
            travis_terminate 0
          fi

          if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
            COMMIT_RANGE="$TRAVIS_BRANCH..HEAD"

            git diff --name-only $COMMIT_RANGE | grep -qE '^entry_types/scrolled/package/src/' || {
              echo "Stopping job: No changes to pageflow-scrolled package."
              travis_terminate 0
            }
          fi
        - yarn install
        - (cd entry_types/scrolled; bundle exec rake pageflow_scrolled:dummy)
      script:
        - |
          export PAGEFLOW_PAPERCLIP_S3_ROOT=master
          export PAGEFLOW_SCROLLED_DB_SEED_SKIP_FILES=$([[ $ON_UPSTREAM_MASTER == "true" ]] && echo "false" || echo "true")
          export S3_BUCKET=de-codevise-pageflow-storybook-seed
          export S3_ACCESS_KEY=$STORYBOOK_SEED_S3_ACCESS_KEY
          export S3_SECRET_KEY=$STORYBOOK_SEED_S3_SECRET_KEY
          export S3_HOST_NAME=s3-eu-west-1.amazonaws.com
          export S3_REGION=eu-west-1
          export S3_HOST_ALIAS=de-codevise-pageflow-storybook-seed.s3-eu-west-1.amazonaws.com
          export S3_PROTOCOL=https
          export PT=b55731926f7bcb9344a0b3ff662613954a4137d3c21c1be748e9929823f19b08
        - (cd entry_types/scrolled; bundle exec rake pageflow_scrolled:storybook:seed:setup[package/.storybook/seed.json])
        - (cd entry_types/scrolled/package; yarn run snapshot)

deploy:
  provider: pages
  repo: tf/pageflow-scrolled-storybook
  skip_cleanup: true
  github_token: $CODEVISE_BOT_PERSONAL_TOKEN2
  keep_history: true
  local_dir: entry_types/scrolled/package/.storybook/out
  on:
    branch: gh-travis
    repo: tf/pageflow